// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: envoy/extensions/filters/http/ext_proc/v3/processing_mode.proto

package v3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeaderSendMode int32

const (
	HeaderSendMode_DEFAULT HeaderSendMode = 0
	HeaderSendMode_SEND    HeaderSendMode = 1
	HeaderSendMode_SKIP    HeaderSendMode = 2
)

// Enum value maps for HeaderSendMode.
var (
	HeaderSendMode_name = map[int32]string{
		0: "DEFAULT",
		1: "SEND",
		2: "SKIP",
	}
	HeaderSendMode_value = map[string]int32{
		"DEFAULT": 0,
		"SEND":    1,
		"SKIP":    2,
	}
)

func (x HeaderSendMode) Enum() *HeaderSendMode {
	p := new(HeaderSendMode)
	*p = x
	return p
}

func (x HeaderSendMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeaderSendMode) Descriptor() protoreflect.EnumDescriptor {
	return file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_enumTypes[0].Descriptor()
}

func (HeaderSendMode) Type() protoreflect.EnumType {
	return &file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_enumTypes[0]
}

func (x HeaderSendMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeaderSendMode.Descriptor instead.
func (HeaderSendMode) EnumDescriptor() ([]byte, []int) {
	return file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_rawDescGZIP(), []int{0}
}

type BodySendMode int32

const (
	BodySendMode_NONE                 BodySendMode = 0
	BodySendMode_STREAMED             BodySendMode = 1
	BodySendMode_BUFFERED             BodySendMode = 2
	BodySendMode_BUFFERED_PARTIAL     BodySendMode = 3
	BodySendMode_FULL_DUPLEX_STREAMED BodySendMode = 4
)

// Enum value maps for BodySendMode.
var (
	BodySendMode_name = map[int32]string{
		0: "NONE",
		1: "STREAMED",
		2: "BUFFERED",
		3: "BUFFERED_PARTIAL",
		4: "FULL_DUPLEX_STREAMED",
	}
	BodySendMode_value = map[string]int32{
		"NONE":                 0,
		"STREAMED":             1,
		"BUFFERED":             2,
		"BUFFERED_PARTIAL":     3,
		"FULL_DUPLEX_STREAMED": 4,
	}
)

func (x BodySendMode) Enum() *BodySendMode {
	p := new(BodySendMode)
	*p = x
	return p
}

func (x BodySendMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BodySendMode) Descriptor() protoreflect.EnumDescriptor {
	return file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_enumTypes[1].Descriptor()
}

func (BodySendMode) Type() protoreflect.EnumType {
	return &file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_enumTypes[1]
}

func (x BodySendMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BodySendMode.Descriptor instead.
func (BodySendMode) EnumDescriptor() ([]byte, []int) {
	return file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_rawDescGZIP(), []int{1}
}

type ProcessingMode struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RequestHeadersMode   HeaderSendMode         `protobuf:"varint,1,opt,name=request_headers_mode,json=requestHeadersMode,proto3,enum=envoy.extensions.filters.http.ext_proc.v3.HeaderSendMode" json:"request_headers_mode,omitempty"`
	ResponseHeadersMode  HeaderSendMode         `protobuf:"varint,2,opt,name=response_headers_mode,json=responseHeadersMode,proto3,enum=envoy.extensions.filters.http.ext_proc.v3.HeaderSendMode" json:"response_headers_mode,omitempty"`
	RequestBodyMode      BodySendMode           `protobuf:"varint,3,opt,name=request_body_mode,json=requestBodyMode,proto3,enum=envoy.extensions.filters.http.ext_proc.v3.BodySendMode" json:"request_body_mode,omitempty"`
	ResponseBodyMode     BodySendMode           `protobuf:"varint,4,opt,name=response_body_mode,json=responseBodyMode,proto3,enum=envoy.extensions.filters.http.ext_proc.v3.BodySendMode" json:"response_body_mode,omitempty"`
	RequestTrailersMode  HeaderSendMode         `protobuf:"varint,5,opt,name=request_trailers_mode,json=requestTrailersMode,proto3,enum=envoy.extensions.filters.http.ext_proc.v3.HeaderSendMode" json:"request_trailers_mode,omitempty"`
	ResponseTrailersMode HeaderSendMode         `protobuf:"varint,6,opt,name=response_trailers_mode,json=responseTrailersMode,proto3,enum=envoy.extensions.filters.http.ext_proc.v3.HeaderSendMode" json:"response_trailers_mode,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ProcessingMode) Reset() {
	*x = ProcessingMode{}
	mi := &file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingMode) ProtoMessage() {}

func (x *ProcessingMode) ProtoReflect() protoreflect.Message {
	mi := &file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingMode.ProtoReflect.Descriptor instead.
func (*ProcessingMode) Descriptor() ([]byte, []int) {
	return file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessingMode) GetRequestHeadersMode() HeaderSendMode {
	if x != nil {
		return x.RequestHeadersMode
	}
	return HeaderSendMode_DEFAULT
}

func (x *ProcessingMode) GetResponseHeadersMode() HeaderSendMode {
	if x != nil {
		return x.ResponseHeadersMode
	}
	return HeaderSendMode_DEFAULT
}

func (x *ProcessingMode) GetRequestBodyMode() BodySendMode {
	if x != nil {
		return x.RequestBodyMode
	}
	return BodySendMode_NONE
}

func (x *ProcessingMode) GetResponseBodyMode() BodySendMode {
	if x != nil {
		return x.ResponseBodyMode
	}
	return BodySendMode_NONE
}

func (x *ProcessingMode) GetRequestTrailersMode() HeaderSendMode {
	if x != nil {
		return x.RequestTrailersMode
	}
	return HeaderSendMode_DEFAULT
}

func (x *ProcessingMode) GetResponseTrailersMode() HeaderSendMode {
	if x != nil {
		return x.ResponseTrailersMode
	}
	return HeaderSendMode_DEFAULT
}

var File_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto protoreflect.FileDescriptor

const file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_rawDesc = "" +
	"\n" +
	"?envoy/extensions/filters/http/ext_proc/v3/processing_mode.proto\x12)envoy.extensions.filters.http.ext_proc.v3\"\x98\x05\n" +
	"\x0eProcessingMode\x12k\n" +
	"\x14request_headers_mode\x18\x01 \x01(\x0e29.envoy.extensions.filters.http.ext_proc.v3.HeaderSendModeR\x12requestHeadersMode\x12m\n" +
	"\x15response_headers_mode\x18\x02 \x01(\x0e29.envoy.extensions.filters.http.ext_proc.v3.HeaderSendModeR\x13responseHeadersMode\x12c\n" +
	"\x11request_body_mode\x18\x03 \x01(\x0e27.envoy.extensions.filters.http.ext_proc.v3.BodySendModeR\x0frequestBodyMode\x12e\n" +
	"\x12response_body_mode\x18\x04 \x01(\x0e27.envoy.extensions.filters.http.ext_proc.v3.BodySendModeR\x10responseBodyMode\x12m\n" +
	"\x15request_trailers_mode\x18\x05 \x01(\x0e29.envoy.extensions.filters.http.ext_proc.v3.HeaderSendModeR\x13requestTrailersMode\x12o\n" +
	"\x16response_trailers_mode\x18\x06 \x01(\x0e29.envoy.extensions.filters.http.ext_proc.v3.HeaderSendModeR\x14responseTrailersMode*1\n" +
	"\x0eHeaderSendMode\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\b\n" +
	"\x04SEND\x10\x01\x12\b\n" +
	"\x04SKIP\x10\x02*d\n" +
	"\fBodySendMode\x12\b\n" +
	"\x04NONE\x10\x00\x12\f\n" +
	"\bSTREAMED\x10\x01\x12\f\n" +
	"\bBUFFERED\x10\x02\x12\x14\n" +
	"\x10BUFFERED_PARTIAL\x10\x03\x12\x18\n" +
	"\x14FULL_DUPLEX_STREAMED\x10\x04BSZQgithub.com/traefik/traefik/v3/pkg/proto/envoy/extensions/filters/http/ext_proc/v3b\x06proto3"

var (
	file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_rawDescOnce sync.Once
	file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_rawDescData []byte
)

func file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_rawDescGZIP() []byte {
	file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_rawDescOnce.Do(func() {
		file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_rawDesc), len(file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_rawDesc)))
	})
	return file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_rawDescData
}

var file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_goTypes = []any{
	(HeaderSendMode)(0),    // 0: envoy.extensions.filters.http.ext_proc.v3.HeaderSendMode
	(BodySendMode)(0),      // 1: envoy.extensions.filters.http.ext_proc.v3.BodySendMode
	(*ProcessingMode)(nil), // 2: envoy.extensions.filters.http.ext_proc.v3.ProcessingMode
}
var file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_depIdxs = []int32{
	0, // 0: envoy.extensions.filters.http.ext_proc.v3.ProcessingMode.request_headers_mode:type_name -> envoy.extensions.filters.http.ext_proc.v3.HeaderSendMode
	0, // 1: envoy.extensions.filters.http.ext_proc.v3.ProcessingMode.response_headers_mode:type_name -> envoy.extensions.filters.http.ext_proc.v3.HeaderSendMode
	1, // 2: envoy.extensions.filters.http.ext_proc.v3.ProcessingMode.request_body_mode:type_name -> envoy.extensions.filters.http.ext_proc.v3.BodySendMode
	1, // 3: envoy.extensions.filters.http.ext_proc.v3.ProcessingMode.response_body_mode:type_name -> envoy.extensions.filters.http.ext_proc.v3.BodySendMode
	0, // 4: envoy.extensions.filters.http.ext_proc.v3.ProcessingMode.request_trailers_mode:type_name -> envoy.extensions.filters.http.ext_proc.v3.HeaderSendMode
	0, // 5: envoy.extensions.filters.http.ext_proc.v3.ProcessingMode.response_trailers_mode:type_name -> envoy.extensions.filters.http.ext_proc.v3.HeaderSendMode
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_init() }
func file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_init() {
	if File_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_rawDesc), len(file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_goTypes,
		DependencyIndexes: file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_depIdxs,
		EnumInfos:         file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_enumTypes,
		MessageInfos:      file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_msgTypes,
	}.Build()
	File_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto = out.File
	file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_goTypes = nil
	file_envoy_extensions_filters_http_ext_proc_v3_processing_mode_proto_depIdxs = nil
}
